name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          
      - name: Install Buildozer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential libssl-dev libffi-dev python3-dev python3-venv python3-wheel unzip libncurses5-dev libncursesw5-dev libzmq3-dev libgdbm-dev libnss3-dev libreadline-dev libsqlite3-dev wget libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev libffi-dev libdb-dev libmpdec-dev libbluetooth-dev libglib2.0-dev libgl1-mesa-dev aidl lib32stdc++6 lib32z1

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer

      - name: Initialize Buildozer and build APK
        run: |
          buildozer init
          buildozer -v android debug
